sudo: false

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  # --ignore-platform-reqs, because https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2722
  - if [[ "${TRAVIS_PHP_VERSION}" != "7.0" ]]; then composer update -n --prefer-dist --ignore-platform-reqs; fi
  - if [[ "${TRAVIS_PHP_VERSION}" == "7.0" ]]; then composer update -n --prefer-dist; fi
  - composer require --dev php-coveralls/php-coveralls ^2.0.0 --ignore-platform-reqs

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - php vendor/bin/coveralls -v

cache:
  directories:
    - $HOME/.composer/cache/files
